name: Build

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo build --release

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: binary-${{ matrix.os }}
          path: |
            target/release/*
            !target/release/*.d
            !target/release/*.rlib
            !target/release/*.rmeta
            !target/release/build
            !target/release/deps
            !target/release/examples
            !target/release/incremental
          if-no-files-found: error
